apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-minecraft-mod-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Y-RyuZU/PrivateMinecraftModServer.git'
    targetRevision: main
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m