apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: create-astral-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi