apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: create-astral-minecraft-server
  template:
    metadata:
      labels:
        app: create-astral-minecraft-server
    spec:
      containers:
      - name: minecraft
        env:
        - name: TYPE
          value: "FORGE"
        - name: VERSION
          value: "1.20.1"
        - name: MEMORY
          value: "4G"
        - name: FORGE_VERSION
          value: "47.2.0"
        - name: MODPACK_URL
          value: "https://example.com/create-astral-modpack.zip"  # Replace with actual modpack URL
        resources:
          requests:
            memory: "12Gi"
            cpu: "6"
          limits:
            memory: "14Gi"
            cpu: "8"