apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: create-astral-minecraft-server
  template:
    metadata:
      labels:
        app: create-astral-minecraft-server
    spec:
      containers:
      - name: minecraft
        image: ghcr.io/claraphyll/create-astral:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "12G"
        - name: USE_AIKAR_FLAGS
          value: "true"
        - name: RCON_ENABLED
          value: "true"
        - name: RCON_PASSWORD
          value: "rcon123"  # Change this password
        resources:
          requests:
            memory: "14Gi"
            cpu: "6"
          limits:
            memory: "14Gi"
            cpu: "7"