apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: NodePort
  selector:
    app: create-astral-minecraft-server
  ports:
  - name: minecraft
    nodePort: 30565
  - name: rcon
    nodePort: 30575