# For small world files (< 1MB each)
# Uncomment and use this if you have small world files
#
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: minecraft-world-data
#   namespace: minecraft
# binaryData:
#   # Add your world files here (base64 encoded)
#   # level.dat: <base64-encoded-file>
#   # region/r.0.0.mca: <base64-encoded-file>
#
# ---
# # Then add this to your deployment patch:
# # spec:
# #   template:
# #     spec:
# #       containers:
# #       - name: minecraft
# #         volumeMounts:
# #         - name: world-files
# #           mountPath: /data/world
# #       volumes:
# #       - name: world-files
# #         configMap:
# #           name: minecraft-world-data