apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: atm9-minecraft-server
  template:
    metadata:
      labels:
        app: atm9-minecraft-server
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FORGE"
        - name: VERSION
          value: "1.20.1"
        - name: FORGE_VERSION
          value: "47.4.0"
        - name: MEMORY
          value: "12G"
        - name: USE_AIKAR_FLAGS
          value: "true"
        - name: RCON_ENABLED
          value: "true"
        - name: RCON_PASSWORD
          value: "rcon123"
        resources:
          requests:
            memory: "14Gi"
            cpu: "6"
          limits:
            memory: "16Gi"
            cpu: "8"