apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: atm9-
commonLabels:
  app.kubernetes.io/instance: atm9
  minecraft-type: modded

resources:
  - ../../base
  - persistent-volume.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: minecraft-server
  - path: service-patch.yaml
    target:
      kind: Service
      name: minecraft-server
  - path: pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: minecraft-pvc