apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: LoadBalancer
  selector:
    app: create-astral-minecraft-server
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
  - name: rcon
    port: 25575
    targetPort: 25575
    protocol: TCP