apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: private-minecraft
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "VANILLA"
        - name: VERSION
          value: "LATEST"
        - name: MEMORY
          value: "2G"
        - name: USE_AIKAR_FLAGS
          value: "true"
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        - containerPort: 25575
          name: rcon
          protocol: TCP
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-pvc