apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: minecraft
  app.kubernetes.io/component: game-server

resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml